
# 使用 Nginx 托管静态文件
FROM nginx:latest

# 删除默认的 Nginx 配置文件
RUN rm -rf /usr/share/nginx/html/*


COPY editor /usr/share/nginx/html/
# 将前端构建结果复制到 Nginx 的默认目录
RUN sed -i 's/127.0.0.1:9090/127.0.0.1:9099/g' "/usr/share/nginx/html/config/config.js"
# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]